1730146756: Error logs for machine_id. Tested  225 instances
29266:13378244 No Direct Ports found get_status_msg = running
27768:13378222 ERROR 2: Test All GPU ResNet50 failed. Benchmarking ResNet50 on batch size 1024 with 8 GPUs
 Traceback (most recent call last):
  File "/pytorch-benchmark-volta/testAllGpusResNet50.py", line 91, in <module>
    main()
  File "/pytorch-benchmark-volta/testAllGpusResNet50.py", line 84, in main
    raise e
  File "/pytorch-benchmark-volta/testAllGpusResNet50.py", line 64, in main
    model(img)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    inputs, module_kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/data_parallel.py", line 207, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/scatter_gather.py", line 88, in scatter_kwargs
    scattered_inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/scatter_gather.py", line 75, in scatter
    res = scatter_map(inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/scatter_gather.py", line 62, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/scatter_gather.py", line 58, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py", line 104, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/comm.py", line 205, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
29260:13378242 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 113] No route to host>
27184:13378301 No Direct Ports found get_status_msg = running
18740:13378297 13378297  Error response from daemon: unknown or invalid runtime name: nvidia
25458:13378341 No Direct Ports found get_status_msg = running
28425:13378325 13378325  Error response from daemon: unknown or invalid runtime name: nvidia
29041:13378332  Error: failed to start containers: C.13378332
28421:13378243 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
29390:13378394 No Direct Ports found get_status_msg = running
29430:13378328  Error: failed to start containers: C.13378328
27610:13378388  Error: failed to start containers: C.13378388
25960:13378295 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
27466:13378384 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
28995:13378447 No Direct Ports found get_status_msg = running
28450:13378383 13378383  Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp [2a03:2880:f11b:83:face:b00c:0:25de]:443: connect: network is unreachable
26520:13378437  Error: failed to start containers: C.13378437
29434:13378330 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
22306:13378385 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
29116:13378334 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
29391:13378438 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
28795:13378335 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
28260:13378440 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
18599:13378477 No Direct Ports found get_status_msg = running
18599:13378439  Error: failed to start containers: C.13378439
28473:13378468 13378468  Error response from daemon: unknown or invalid runtime name: nvidia
2255:13378475  Error: failed to start containers: C.13378475
22459:13378531 No Direct Ports found get_status_msg = running
29345:13378464 Unable to find image 'jjziets/vasttest_latest/ssh:latest' locally
Error response from daemon: pull access denied for jjziets/vasttest_latest/ssh, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
25402:13378526 ERROR 2: Test All GPU ResNet50 failed. Failed to execute the model with any batch size
 
26520:13378393 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
17472:13378527 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 113] No route to host>
27893:13378572 No Direct Ports found get_status_msg = running
25069:13378564  went offline
21553:13378569 ERROR 1: System requirements test failed. System total memory is less than the sum of all the GPUs VRAM.
 
28473:13378467 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
29037:13378476 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
20616:13378568 ERROR 1: System requirements test failed. No GPUs found.
 
12337:13378625 No Direct Ports found get_status_msg = running
29125:13378524 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
27235:13378653 No Direct Ports found get_status_msg = running
27235:13378241 Time exceeded get_status_msg = loading
27716:13378597 ERROR: Failed to connect or retrieve data: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>
27716:13378597 ERROR: Failed to connect or retrieve data: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>
24548:13378562 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
29227:13378648 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 113] No route to host>
29051:13378670 No Direct Ports found get_status_msg = running
29368:13378646 ERROR 1: System requirements test failed. System total memory is less than the sum of all the GPUs VRAM.
 
29177:13378649 13378649  Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 127.0.0.53:53: read udp 127.0.0.1:40854->127.0.0.53:53: i/o timeout
29334:13378622 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
27141:13378668 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 113] No route to host>
25330:13378714 No Direct Ports found get_status_msg = running
27777:13378704 ERROR 2: Test All GPU ResNet50 failed. Benchmarking ResNet50 on batch size 1024 with 8 GPUs
 Traceback (most recent call last):
  File "/pytorch-benchmark-volta/testAllGpusResNet50.py", line 91, in <module>
    main()
  File "/pytorch-benchmark-volta/testAllGpusResNet50.py", line 84, in main
    raise e
  File "/pytorch-benchmark-volta/testAllGpusResNet50.py", line 64, in main
    model(img)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    inputs, module_kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/data_parallel.py", line 207, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/scatter_gather.py", line 88, in scatter_kwargs
    scattered_inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/scatter_gather.py", line 75, in scatter
    res = scatter_map(inputs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/scatter_gather.py", line 62, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/scatter_gather.py", line 58, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/_functions.py", line 104, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/comm.py", line 205, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: CUDA error: uncorrectable ECC error encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
27238:13378651 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
27236:13378652 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
28750:13378741 No Direct Ports found get_status_msg = running
28750:13378696  Error: failed to start containers: C.13378696
28750:13378739 13378739  Error response from daemon: Head "https://registry-1.docker.io/v2/jjziets/vasttest/manifests/latest": Get "https://auth.docker.io/token?scope=repository%3Ajjziets%2Fvasttest%3Apull&service=registry.docker.io": net/http: TLS handshake timeout
27233:13378664 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
29255:13378763 No Direct Ports found get_status_msg = running
29255:13378441 Time exceeded get_status_msg = loading
25221:13378667 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
29188:13378697 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
22393:13378797 No Direct Ports found get_status_msg = running
22393:13378445 Time exceeded get_status_msg = loading
28759:13378788  Error: failed to start containers: C.13378788
22394:13378796 ERROR 1: System requirements test failed.  Traceback (most recent call last):
  File "/pytorch-benchmark-volta/systemreqtest.py", line 55, in <module>
    sys.exit(main())
  File "/pytorch-benchmark-volta/systemreqtest.py", line 15, in main
    first_gpu_model = torch.cuda.get_device_name(0)
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 493, in get_device_name
    return get_device_properties(device).name
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 523, in get_device_properties
    _lazy_init()  # will define _get_device_properties
  File "/usr/local/lib/python3.10/dist-packages/torch/cuda/__init__.py", line 319, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA driver initialization failed, you might not have a CUDA gpu.
14465:13378791 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 113] No route to host>
26434:13378847 No Direct Ports found get_status_msg = running
26434:13378644  Error: failed to start containers: C.13378644
18386:13378846 ERROR 1: System requirements test failed. System total memory is less than the sum of all the GPUs VRAM.
 
27169:13378839 ERROR: Failed to connect or retrieve data: <urlopen error [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1007)>
27137:13378871 No Direct Ports found get_status_msg = running
29134:13378929 No Direct Ports found get_status_msg = running
29134:13378563 Time exceeded get_status_msg = loading
29134:13378565 Time exceeded get_status_msg = loading
25802:13378922 ERROR 1: System requirements test failed. System total memory is less than the sum of all the GPUs VRAM.
 
28956:13378866 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
28270:13378955 No Direct Ports found get_status_msg = running
28270:13378590 Time exceeded get_status_msg = loading
28270:13378618 Time exceeded get_status_msg = loading
29420:13378867  Error: failed to start containers: C.13378867
26261:13378945  went offline
16147:13378841 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
29328:13378984 No Direct Ports found get_status_msg = running
18726:13378760 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
17256:13378969 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 113] No route to host>
29321:13379023 No Direct Ports found get_status_msg = running
29500:13379022 No Direct Ports found get_status_msg = running
29500:13378926  Error: failed to start containers: C.13378926
28077:13378703 Time exceeded get_status_msg = loading
28077:13379020 Time exceeded get_status_msg 13379020
28072:13378982 No Direct Ports found get_status_msg = running
28164:13378952 No Direct Ports found get_status_msg = running
28684:13378927 No Direct Ports found get_status_msg = running
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 Time exceeded get_status_msg 13378231
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
28351:13378230 No Direct Ports found get_status_msg = running
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 110] Connection timed out>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
21619:13378231 ERROR: Failed to connect or retrieve data: <urlopen error [Errno 111] Connection refused>
